MIN_SETUP = 8
MIN_CLEANUP = 6
MAX_SHIFTS = 4
MIN_SHIFTS = 2
MAX_CONSECUTIVE_SHIFTS = 1
MODE = "regular" # shadowing or regular

if MODE == "shadowing":
    NUM_SETUP_LEADERS = 1
    NUM_CLEANUP_LEADERS = 1
    NUM_SETUP_SHADOWS = 1
    NUM_CLEANUP_SHADOWS = 1
else:
    NUM_SETUP_LEADERS = 2
    NUM_CLEANUP_LEADERS = 2
    NUM_SETUP_SHADOWS = 0
    NUM_CLEANUP_SHADOWS = 0
